
services:
  minio:
    image: quay.io/minio/minio
    container_name: minio-dbt
    hostname: minio
    profiles:
      - dbt 
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin


  postgres:
    image: postgres:15
    container_name: minio-postgres
    profiles:
      - dbt
    environment:
      POSTGRES_USER: dbt
      POSTGRES_PASSWORD: dbt
      POSTGRES_DB: analytics
    ports:
      - "5432:5432"